### ISSUE TITLE
Document the github helm configuration values

### ISSUE THREAD

**Issue by rberrelleza** [okteto/docs#191]
Currently, the values described on https://www.okteto.com/docs/enterprise/administration/github/#adding-the-github-app-configuration-to-okteto are not documented anywhere else. 

I believe that we should include them on https://www.okteto.com/docs/enterprise/install/deployment/#configuration-file

**Comment by pchico83** [comment]
Also, we should document that `clientSecret` can be configured by adding `GITHUB_INTEGRATION_CLIENTSECRET` to the `okteto-cloud-secret`. `appPrivateKey` can be also configured by adding `GITHUB_APP_PRIVATE_KEY` to the `okteto-cloud-secret`. Both values must be base64 encoded

**Comment by rberrelleza** [comment]
@pchico83 do you have a sample?
