### ISSUE TITLE
Improve README to mention about building website locally using Okteto

### ISSUE THREAD

**Issue by NitishKumar06** [okteto/docs#327]
## **This is a feature Request**
In order to [develop a website locally](https://github.com/okteto/docs#-develop-locally), we're using _yarn_. The commands are very simple and easy to run the website locally. However, there is a need for the required version of _yarn_ and _Node_ to be installed as mentioned in the above-referenced text. 

Building the website locally **using okteto** doesn't require any of the versions/dependencies to be installed. The [getting-started guide](https://www.okteto.com/docs/using-dev-envs/) is a good place to start learning about okteto. However, we're missing the information on building the website & core locally using okteto.

 This is not the only reason to mention building the website locally using okteto. Any reader who is going through the Readme initially will able to grasp very easily the problem okteto is trying to solve. Instead of directly moving to deploy our own application, it'd be much better if the users are shown a short way of building okteto's website & core locally. 

**Reference:** https://community.okteto.com/t/unable-to-build-website-locally-using-yarn-resulting-in-5-errors/602/2?u=nitishkumar06

**How to do it**

Update the [develop a website [locally](https://github.com/okteto/docs#-develop-locally) section to mention building the website along with _yarn_.

**Comment by NitishKumar06** [comment]
I'd like to work on this!

**Comment by rberrelleza** [comment]
@NitishKumar06 sounds good!
