### ISSUE TITLE
document `--platform` flag for `okteto build`

### ISSUE THREAD

**Issue by RinkiyaKeDad** [okteto/docs#397]
`okteto build` has `--platform` flag which allows specifying what platform to build the container images for. While documenting we can also mention a common use case for this where if you're on an ARM based machine but using a non ARM cluster then you will need to run `okteto build --platform linux/amd64` to build the images correctly so that they run on your cluster.

**Comment by NitishKumar06** [comment]
I'd like to take this up. Please assign this to me!

**Comment by NitishKumar06** [comment]
I've started working on this issue and would like to know couple of things before pushing the changes:

1. Where do we actually want to implement these changes? Is it [here](https://www.okteto.com/docs/reference/cli/#build)?
2. By documenting the flag `--platform`, do we intend to write a description of the flag and explain its use case? If Yes, I find that there's no such description written for other flags such as _--file, --no-cache_
