### ISSUE TITLE
As an End User, I'd like to access documentation via docs.okteto.com

### ISSUE THREAD

**Issue by davidpthomas** [okteto/docs#398]
People's brains work differently when it comes to _guessing_ where docs are for an organization.  e.g. docs.company.com or company.com/docs.  Me personally, I always default to docs.company.com so it get's my vote ;)

Suggest creating a DNS alias 'docs.okteto.com' that redirects to the current 'okteto.com/docs'.

HTH!

**Comment by rberrelleza** [comment]
Done!
