### ISSUE TITLE
Default values are not consistently written/styled in CLI reference

### ISSUE THREAD

**Issue by viddo** [okteto/docs#403]
https://www.okteto.com/docs/reference/cli

A few examples:
| <img width="549" alt="Screenshot 2023-05-19 at 13 29 50" src="https://github.com/okteto/docs/assets/978461/b5538688-bc5b-475a-8534-cc4ea8fe2ebd"> | <img width="302" alt="Screenshot 2023-05-19 at 13 37 34" src="https://github.com/okteto/docs/assets/978461/ad323f0f-f1bd-4f37-9351-61f5e0a9b7e9"> }
| - | - |

- The font-size and baseline is different from the general non-`<code>` text on same line (16 vs 18px, code blocks rendered below baseline)
- The wording different depending on command, e.g. `defaults to false`, `default false`, `default: false`, etc. Similar for other values, e.g. _default: "foobar"_

These are minor issues obviously, but could we fix these inconsistencies? Would make it easier on eyes when skimming docs. :) 

BTW, since already using tables for options, perhaps could consider putting default values in a separate column? Would also help to see which options have default or no value.

**Comment by codyjlandstrom** [comment]
Noticed this too: https://github.com/okteto/docs/pull/696
