### ISSUE TITLE
Can't find environment section on okteto manifest reference through search

### ISSUE THREAD

**Issue by viddo** [okteto/docs#413]
## Expected behavior

To find the reference section for how to add environment variables for a dev container on the okteto.yaml manifest, i.e. https://www.okteto.com/docs/reference/manifest/#environment-string-optional

## Actual behavior

Couldn't find it through Algolia search, had to use in-browser search to find it.

Example snapshot from one search search:
<img width="1605" alt="Screenshot 2023-05-29 at 11 27 42" src="https://github.com/okteto/docs/assets/978461/345878df-ec94-4c16-9542-59415c5f20f7">
_Search not showing section that can be seen in the background_

## Steps to reproduce

1. Click search / Cmd+K (Mac)
1. Search for any of `environment`, `environment variable`, `env var` or similar to try to find the aforementioned section.

## Observations 

- I had to resort to use the in-browser search on the reference page instead. Not a great experience and unnecessary friction.
-  After finding the section and knowing the docs full text, by using exact phrase I could find it, `"environment variables to"`, so definitely indexed but unclear why it's not appearing unless searching with long exact phrase.

**Comment by kumarankit999** [comment]
Should I work on this

**Comment by omnomagonz** [comment]
@viddo Do we think this could be an issue with Algolia and running the re-indexing flow might help or does this seem to be something outside of that context?

**Comment by viddo** [comment]
@omnomagonz ¯\_(ツ)_/¯  now it seems to work so sounds like a problem with Algolia indexing not worker proper at all times… closing
