### ISSUE TITLE
document labels for dev environments

### ISSUE THREAD

**Issue by AdrianPedriza** [okteto/docs#510]
with the release of okteto cli `2.21` comes the possibility to add labels to the dev environment as well as to list them. Documentation about it should be created.

**Comment by rlamana** [comment]
Migrated to Jira: https://okteto.atlassian.net/browse/LAKE-12?atlOrigin=eyJpIjoiZjMzZDQ4YWZkYzVlNDMzNDkwM2NiZDExNDlkOTQ5MjQiLCJwIjoiaiJ9
