### ISSUE TITLE
update docs to Docusaurus 3.0

### ISSUE THREAD

**Issue by rberrelleza** [okteto/docs#582]
We are currently on an early 2.X version of docusaurus. We should upgrade to the 3.1.X version as soon as possible to avoid compatibility, security, and future migration issues.

**Comment by codyjlandstrom** [comment]
Updated!

**Comment by codyjlandstrom** [comment]
Updated!

**Comment by codyjlandstrom** [comment]
Updated!

**Comment by codyjlandstrom** [comment]
Updated!
