### ISSUE TITLE
Document how to use Okteto Stack fragments

### ISSUE THREAD

**Issue by pchico83** [okteto/docs#7]
For reference, this is how it is documented in the compose spec:
https://github.com/compose-spec/compose-spec/blob/master/spec.md#fragments

**Comment by RinkiyaKeDad** [comment]
@pchico83 is this issue till relevant?

**Comment by pchico83** [comment]
> @pchico83 is this issue till relevant?

fragments are very useful to reuse parts of your yaml. we are using them here https://github.com/okteto/app/blob/master/okteto.yml#L45

maybe this is good content for the community forun

**Comment by rberrelleza** [comment]
I'm going to close this, but can you answer it here @pchico83 ? https://community.okteto.com/t/can-i-use-yaml-anchors-with-okteto/48
